//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("VendasModel", "FK_Venda_Cliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProjetoVendas.Model.Cliente), "Venda", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjetoVendas.Model.Venda), true)]
[assembly: EdmRelationshipAttribute("VendasModel", "FK_ItemCompra_Compra", "Compra", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProjetoVendas.Model.Compra), "ItemCompra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjetoVendas.Model.ItemCompra), true)]
[assembly: EdmRelationshipAttribute("VendasModel", "FK_Produto_Departamento", "Departamento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProjetoVendas.Model.Departamento), "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjetoVendas.Model.Produto), true)]
[assembly: EdmRelationshipAttribute("VendasModel", "FK_ItemCompra_Produto", "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProjetoVendas.Model.Produto), "ItemCompra", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjetoVendas.Model.ItemCompra), true)]
[assembly: EdmRelationshipAttribute("VendasModel", "FK_ItemVenda_Produto", "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProjetoVendas.Model.Produto), "ItemVenda", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjetoVendas.Model.ItemVenda), true)]
[assembly: EdmRelationshipAttribute("VendasModel", "FK_ItemVenda_Venda", "Venda", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProjetoVendas.Model.Venda), "ItemVenda", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjetoVendas.Model.ItemVenda), true)]
[assembly: EdmRelationshipAttribute("VendasModel", "FK_Movimentacao_Produto", "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProjetoVendas.Model.Produto), "Movimentacao", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjetoVendas.Model.Movimentacao), true)]
[assembly: EdmRelationshipAttribute("VendasModel", "FK_Venda_Vendedor", "Vendedor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProjetoVendas.Model.Vendedor), "Venda", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjetoVendas.Model.Venda), true)]

#endregion

namespace ProjetoVendas.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VendasEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VendasEntities object using the connection string found in the 'VendasEntities' section of the application configuration file.
        /// </summary>
        public VendasEntities() : base("name=VendasEntities", "VendasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VendasEntities object.
        /// </summary>
        public VendasEntities(string connectionString) : base(connectionString, "VendasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VendasEntities object.
        /// </summary>
        public VendasEntities(EntityConnection connection) : base(connection, "VendasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Compra> Compra
        {
            get
            {
                if ((_Compra == null))
                {
                    _Compra = base.CreateObjectSet<Compra>("Compra");
                }
                return _Compra;
            }
        }
        private ObjectSet<Compra> _Compra;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Departamento> Departamento
        {
            get
            {
                if ((_Departamento == null))
                {
                    _Departamento = base.CreateObjectSet<Departamento>("Departamento");
                }
                return _Departamento;
            }
        }
        private ObjectSet<Departamento> _Departamento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemCompra> ItemCompra
        {
            get
            {
                if ((_ItemCompra == null))
                {
                    _ItemCompra = base.CreateObjectSet<ItemCompra>("ItemCompra");
                }
                return _ItemCompra;
            }
        }
        private ObjectSet<ItemCompra> _ItemCompra;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemVenda> ItemVenda
        {
            get
            {
                if ((_ItemVenda == null))
                {
                    _ItemVenda = base.CreateObjectSet<ItemVenda>("ItemVenda");
                }
                return _ItemVenda;
            }
        }
        private ObjectSet<ItemVenda> _ItemVenda;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Movimentacao> Movimentacao
        {
            get
            {
                if ((_Movimentacao == null))
                {
                    _Movimentacao = base.CreateObjectSet<Movimentacao>("Movimentacao");
                }
                return _Movimentacao;
            }
        }
        private ObjectSet<Movimentacao> _Movimentacao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produto> Produto
        {
            get
            {
                if ((_Produto == null))
                {
                    _Produto = base.CreateObjectSet<Produto>("Produto");
                }
                return _Produto;
            }
        }
        private ObjectSet<Produto> _Produto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Venda> Venda
        {
            get
            {
                if ((_Venda == null))
                {
                    _Venda = base.CreateObjectSet<Venda>("Venda");
                }
                return _Venda;
            }
        }
        private ObjectSet<Venda> _Venda;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vendedor> Vendedor
        {
            get
            {
                if ((_Vendedor == null))
                {
                    _Vendedor = base.CreateObjectSet<Vendedor>("Vendedor");
                }
                return _Vendedor;
            }
        }
        private ObjectSet<Vendedor> _Vendedor;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Compra EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompra(Compra compra)
        {
            base.AddObject("Compra", compra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Departamento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDepartamento(Departamento departamento)
        {
            base.AddObject("Departamento", departamento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemCompra EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemCompra(ItemCompra itemCompra)
        {
            base.AddObject("ItemCompra", itemCompra);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemVenda EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemVenda(ItemVenda itemVenda)
        {
            base.AddObject("ItemVenda", itemVenda);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Movimentacao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovimentacao(Movimentacao movimentacao)
        {
            base.AddObject("Movimentacao", movimentacao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduto(Produto produto)
        {
            base.AddObject("Produto", produto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Venda EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVenda(Venda venda)
        {
            base.AddObject("Venda", venda);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vendedor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVendedor(Vendedor vendedor)
        {
            base.AddObject("Vendedor", vendedor);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="idCliente">Initial value of the IdCliente property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="cPF">Initial value of the CPF property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        public static Cliente CreateCliente(global::System.Int32 idCliente, global::System.String nome, global::System.String cPF, global::System.DateTime dataNascimento)
        {
            Cliente cliente = new Cliente();
            cliente.IdCliente = idCliente;
            cliente.Nome = nome;
            cliente.CPF = cPF;
            cliente.DataNascimento = dataNascimento;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.DateTime _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.DateTime value);
        partial void OnDataNascimentoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_Venda_Cliente", "Venda")]
        public EntityCollection<Venda> Venda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venda>("VendasModel.FK_Venda_Cliente", "Venda");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venda>("VendasModel.FK_Venda_Cliente", "Venda", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Compra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Compra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Compra object.
        /// </summary>
        /// <param name="idCompra">Initial value of the IdCompra property.</param>
        /// <param name="dataCompra">Initial value of the DataCompra property.</param>
        /// <param name="fornecedor">Initial value of the Fornecedor property.</param>
        public static Compra CreateCompra(global::System.Int32 idCompra, global::System.DateTime dataCompra, global::System.String fornecedor)
        {
            Compra compra = new Compra();
            compra.IdCompra = idCompra;
            compra.DataCompra = dataCompra;
            compra.Fornecedor = fornecedor;
            return compra;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCompra
        {
            get
            {
                return _IdCompra;
            }
            set
            {
                if (_IdCompra != value)
                {
                    OnIdCompraChanging(value);
                    ReportPropertyChanging("IdCompra");
                    _IdCompra = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCompra");
                    OnIdCompraChanged();
                }
            }
        }
        private global::System.Int32 _IdCompra;
        partial void OnIdCompraChanging(global::System.Int32 value);
        partial void OnIdCompraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCompra
        {
            get
            {
                return _DataCompra;
            }
            set
            {
                OnDataCompraChanging(value);
                ReportPropertyChanging("DataCompra");
                _DataCompra = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataCompra");
                OnDataCompraChanged();
            }
        }
        private global::System.DateTime _DataCompra;
        partial void OnDataCompraChanging(global::System.DateTime value);
        partial void OnDataCompraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Fornecedor
        {
            get
            {
                return _Fornecedor;
            }
            set
            {
                OnFornecedorChanging(value);
                ReportPropertyChanging("Fornecedor");
                _Fornecedor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Fornecedor");
                OnFornecedorChanged();
            }
        }
        private global::System.String _Fornecedor;
        partial void OnFornecedorChanging(global::System.String value);
        partial void OnFornecedorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_ItemCompra_Compra", "ItemCompra")]
        public EntityCollection<ItemCompra> ItemCompra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemCompra>("VendasModel.FK_ItemCompra_Compra", "ItemCompra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemCompra>("VendasModel.FK_ItemCompra_Compra", "ItemCompra", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Departamento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Departamento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Departamento object.
        /// </summary>
        /// <param name="idDepartamento">Initial value of the IdDepartamento property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Departamento CreateDepartamento(global::System.Int32 idDepartamento, global::System.String descricao)
        {
            Departamento departamento = new Departamento();
            departamento.IdDepartamento = idDepartamento;
            departamento.Descricao = descricao;
            return departamento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDepartamento
        {
            get
            {
                return _IdDepartamento;
            }
            set
            {
                if (_IdDepartamento != value)
                {
                    OnIdDepartamentoChanging(value);
                    ReportPropertyChanging("IdDepartamento");
                    _IdDepartamento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdDepartamento");
                    OnIdDepartamentoChanged();
                }
            }
        }
        private global::System.Int32 _IdDepartamento;
        partial void OnIdDepartamentoChanging(global::System.Int32 value);
        partial void OnIdDepartamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_Produto_Departamento", "Produto")]
        public EntityCollection<Produto> Produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Produto>("VendasModel.FK_Produto_Departamento", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Produto>("VendasModel.FK_Produto_Departamento", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="ItemCompra")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemCompra : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemCompra object.
        /// </summary>
        /// <param name="idProduto">Initial value of the IdProduto property.</param>
        /// <param name="idCompra">Initial value of the IdCompra property.</param>
        /// <param name="quantidade">Initial value of the Quantidade property.</param>
        public static ItemCompra CreateItemCompra(global::System.Int32 idProduto, global::System.Int32 idCompra, global::System.Single quantidade)
        {
            ItemCompra itemCompra = new ItemCompra();
            itemCompra.IdProduto = idProduto;
            itemCompra.IdCompra = idCompra;
            itemCompra.Quantidade = quantidade;
            return itemCompra;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProduto
        {
            get
            {
                return _IdProduto;
            }
            set
            {
                if (_IdProduto != value)
                {
                    OnIdProdutoChanging(value);
                    ReportPropertyChanging("IdProduto");
                    _IdProduto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProduto");
                    OnIdProdutoChanged();
                }
            }
        }
        private global::System.Int32 _IdProduto;
        partial void OnIdProdutoChanging(global::System.Int32 value);
        partial void OnIdProdutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCompra
        {
            get
            {
                return _IdCompra;
            }
            set
            {
                if (_IdCompra != value)
                {
                    OnIdCompraChanging(value);
                    ReportPropertyChanging("IdCompra");
                    _IdCompra = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCompra");
                    OnIdCompraChanged();
                }
            }
        }
        private global::System.Int32 _IdCompra;
        partial void OnIdCompraChanging(global::System.Int32 value);
        partial void OnIdCompraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Quantidade
        {
            get
            {
                return _Quantidade;
            }
            set
            {
                OnQuantidadeChanging(value);
                ReportPropertyChanging("Quantidade");
                _Quantidade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantidade");
                OnQuantidadeChanged();
            }
        }
        private global::System.Single _Quantidade;
        partial void OnQuantidadeChanging(global::System.Single value);
        partial void OnQuantidadeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_ItemCompra_Compra", "Compra")]
        public Compra Compra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("VendasModel.FK_ItemCompra_Compra", "Compra").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("VendasModel.FK_ItemCompra_Compra", "Compra").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Compra> CompraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Compra>("VendasModel.FK_ItemCompra_Compra", "Compra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Compra>("VendasModel.FK_ItemCompra_Compra", "Compra", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_ItemCompra_Produto", "Produto")]
        public Produto Produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("VendasModel.FK_ItemCompra_Produto", "Produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("VendasModel.FK_ItemCompra_Produto", "Produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produto> ProdutoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("VendasModel.FK_ItemCompra_Produto", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produto>("VendasModel.FK_ItemCompra_Produto", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="ItemVenda")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemVenda : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemVenda object.
        /// </summary>
        /// <param name="idProduto">Initial value of the IdProduto property.</param>
        /// <param name="idVenda">Initial value of the IdVenda property.</param>
        /// <param name="quantidade">Initial value of the Quantidade property.</param>
        public static ItemVenda CreateItemVenda(global::System.Int32 idProduto, global::System.Int32 idVenda, global::System.Single quantidade)
        {
            ItemVenda itemVenda = new ItemVenda();
            itemVenda.IdProduto = idProduto;
            itemVenda.IdVenda = idVenda;
            itemVenda.Quantidade = quantidade;
            return itemVenda;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProduto
        {
            get
            {
                return _IdProduto;
            }
            set
            {
                if (_IdProduto != value)
                {
                    OnIdProdutoChanging(value);
                    ReportPropertyChanging("IdProduto");
                    _IdProduto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProduto");
                    OnIdProdutoChanged();
                }
            }
        }
        private global::System.Int32 _IdProduto;
        partial void OnIdProdutoChanging(global::System.Int32 value);
        partial void OnIdProdutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdVenda
        {
            get
            {
                return _IdVenda;
            }
            set
            {
                if (_IdVenda != value)
                {
                    OnIdVendaChanging(value);
                    ReportPropertyChanging("IdVenda");
                    _IdVenda = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdVenda");
                    OnIdVendaChanged();
                }
            }
        }
        private global::System.Int32 _IdVenda;
        partial void OnIdVendaChanging(global::System.Int32 value);
        partial void OnIdVendaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Quantidade
        {
            get
            {
                return _Quantidade;
            }
            set
            {
                OnQuantidadeChanging(value);
                ReportPropertyChanging("Quantidade");
                _Quantidade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantidade");
                OnQuantidadeChanged();
            }
        }
        private global::System.Single _Quantidade;
        partial void OnQuantidadeChanging(global::System.Single value);
        partial void OnQuantidadeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_ItemVenda_Produto", "Produto")]
        public Produto Produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("VendasModel.FK_ItemVenda_Produto", "Produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("VendasModel.FK_ItemVenda_Produto", "Produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produto> ProdutoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("VendasModel.FK_ItemVenda_Produto", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produto>("VendasModel.FK_ItemVenda_Produto", "Produto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_ItemVenda_Venda", "Venda")]
        public Venda Venda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venda>("VendasModel.FK_ItemVenda_Venda", "Venda").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venda>("VendasModel.FK_ItemVenda_Venda", "Venda").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Venda> VendaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venda>("VendasModel.FK_ItemVenda_Venda", "Venda");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Venda>("VendasModel.FK_ItemVenda_Venda", "Venda", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Movimentacao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Movimentacao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Movimentacao object.
        /// </summary>
        /// <param name="idMovimentacao">Initial value of the IdMovimentacao property.</param>
        /// <param name="idProduto">Initial value of the IdProduto property.</param>
        /// <param name="quantidade">Initial value of the Quantidade property.</param>
        /// <param name="dataMovimentacao">Initial value of the DataMovimentacao property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        public static Movimentacao CreateMovimentacao(global::System.Int32 idMovimentacao, global::System.Int32 idProduto, global::System.Single quantidade, global::System.DateTime dataMovimentacao, global::System.String tipo)
        {
            Movimentacao movimentacao = new Movimentacao();
            movimentacao.IdMovimentacao = idMovimentacao;
            movimentacao.IdProduto = idProduto;
            movimentacao.Quantidade = quantidade;
            movimentacao.DataMovimentacao = dataMovimentacao;
            movimentacao.Tipo = tipo;
            return movimentacao;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMovimentacao
        {
            get
            {
                return _IdMovimentacao;
            }
            set
            {
                if (_IdMovimentacao != value)
                {
                    OnIdMovimentacaoChanging(value);
                    ReportPropertyChanging("IdMovimentacao");
                    _IdMovimentacao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdMovimentacao");
                    OnIdMovimentacaoChanged();
                }
            }
        }
        private global::System.Int32 _IdMovimentacao;
        partial void OnIdMovimentacaoChanging(global::System.Int32 value);
        partial void OnIdMovimentacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProduto
        {
            get
            {
                return _IdProduto;
            }
            set
            {
                OnIdProdutoChanging(value);
                ReportPropertyChanging("IdProduto");
                _IdProduto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdProduto");
                OnIdProdutoChanged();
            }
        }
        private global::System.Int32 _IdProduto;
        partial void OnIdProdutoChanging(global::System.Int32 value);
        partial void OnIdProdutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Quantidade
        {
            get
            {
                return _Quantidade;
            }
            set
            {
                OnQuantidadeChanging(value);
                ReportPropertyChanging("Quantidade");
                _Quantidade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantidade");
                OnQuantidadeChanged();
            }
        }
        private global::System.Single _Quantidade;
        partial void OnQuantidadeChanging(global::System.Single value);
        partial void OnQuantidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataMovimentacao
        {
            get
            {
                return _DataMovimentacao;
            }
            set
            {
                OnDataMovimentacaoChanging(value);
                ReportPropertyChanging("DataMovimentacao");
                _DataMovimentacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataMovimentacao");
                OnDataMovimentacaoChanged();
            }
        }
        private global::System.DateTime _DataMovimentacao;
        partial void OnDataMovimentacaoChanging(global::System.DateTime value);
        partial void OnDataMovimentacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_Movimentacao_Produto", "Produto")]
        public Produto Produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("VendasModel.FK_Movimentacao_Produto", "Produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("VendasModel.FK_Movimentacao_Produto", "Produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produto> ProdutoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("VendasModel.FK_Movimentacao_Produto", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produto>("VendasModel.FK_Movimentacao_Produto", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produto object.
        /// </summary>
        /// <param name="idProduto">Initial value of the IdProduto property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="valorCompra">Initial value of the ValorCompra property.</param>
        /// <param name="valorVenda">Initial value of the ValorVenda property.</param>
        /// <param name="idDepartamento">Initial value of the IdDepartamento property.</param>
        public static Produto CreateProduto(global::System.Int32 idProduto, global::System.String descricao, global::System.Single valorCompra, global::System.Single valorVenda, global::System.Int32 idDepartamento)
        {
            Produto produto = new Produto();
            produto.IdProduto = idProduto;
            produto.Descricao = descricao;
            produto.ValorCompra = valorCompra;
            produto.ValorVenda = valorVenda;
            produto.IdDepartamento = idDepartamento;
            return produto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProduto
        {
            get
            {
                return _IdProduto;
            }
            set
            {
                if (_IdProduto != value)
                {
                    OnIdProdutoChanging(value);
                    ReportPropertyChanging("IdProduto");
                    _IdProduto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProduto");
                    OnIdProdutoChanged();
                }
            }
        }
        private global::System.Int32 _IdProduto;
        partial void OnIdProdutoChanging(global::System.Int32 value);
        partial void OnIdProdutoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single ValorCompra
        {
            get
            {
                return _ValorCompra;
            }
            set
            {
                OnValorCompraChanging(value);
                ReportPropertyChanging("ValorCompra");
                _ValorCompra = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValorCompra");
                OnValorCompraChanged();
            }
        }
        private global::System.Single _ValorCompra;
        partial void OnValorCompraChanging(global::System.Single value);
        partial void OnValorCompraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single ValorVenda
        {
            get
            {
                return _ValorVenda;
            }
            set
            {
                OnValorVendaChanging(value);
                ReportPropertyChanging("ValorVenda");
                _ValorVenda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValorVenda");
                OnValorVendaChanged();
            }
        }
        private global::System.Single _ValorVenda;
        partial void OnValorVendaChanging(global::System.Single value);
        partial void OnValorVendaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDepartamento
        {
            get
            {
                return _IdDepartamento;
            }
            set
            {
                OnIdDepartamentoChanging(value);
                ReportPropertyChanging("IdDepartamento");
                _IdDepartamento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdDepartamento");
                OnIdDepartamentoChanged();
            }
        }
        private global::System.Int32 _IdDepartamento;
        partial void OnIdDepartamentoChanging(global::System.Int32 value);
        partial void OnIdDepartamentoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_Produto_Departamento", "Departamento")]
        public Departamento Departamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departamento>("VendasModel.FK_Produto_Departamento", "Departamento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departamento>("VendasModel.FK_Produto_Departamento", "Departamento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Departamento> DepartamentoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departamento>("VendasModel.FK_Produto_Departamento", "Departamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Departamento>("VendasModel.FK_Produto_Departamento", "Departamento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_ItemCompra_Produto", "ItemCompra")]
        public EntityCollection<ItemCompra> ItemCompra
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemCompra>("VendasModel.FK_ItemCompra_Produto", "ItemCompra");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemCompra>("VendasModel.FK_ItemCompra_Produto", "ItemCompra", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_ItemVenda_Produto", "ItemVenda")]
        public EntityCollection<ItemVenda> ItemVenda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemVenda>("VendasModel.FK_ItemVenda_Produto", "ItemVenda");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemVenda>("VendasModel.FK_ItemVenda_Produto", "ItemVenda", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_Movimentacao_Produto", "Movimentacao")]
        public EntityCollection<Movimentacao> Movimentacao
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movimentacao>("VendasModel.FK_Movimentacao_Produto", "Movimentacao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movimentacao>("VendasModel.FK_Movimentacao_Produto", "Movimentacao", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Venda")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venda : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Venda object.
        /// </summary>
        /// <param name="idVenda">Initial value of the IdVenda property.</param>
        /// <param name="dataVenda">Initial value of the DataVenda property.</param>
        /// <param name="idCliente">Initial value of the IdCliente property.</param>
        /// <param name="idVendedor">Initial value of the IdVendedor property.</param>
        public static Venda CreateVenda(global::System.Int32 idVenda, global::System.DateTime dataVenda, global::System.Int32 idCliente, global::System.Int32 idVendedor)
        {
            Venda venda = new Venda();
            venda.IdVenda = idVenda;
            venda.DataVenda = dataVenda;
            venda.IdCliente = idCliente;
            venda.IdVendedor = idVendedor;
            return venda;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdVenda
        {
            get
            {
                return _IdVenda;
            }
            set
            {
                if (_IdVenda != value)
                {
                    OnIdVendaChanging(value);
                    ReportPropertyChanging("IdVenda");
                    _IdVenda = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdVenda");
                    OnIdVendaChanged();
                }
            }
        }
        private global::System.Int32 _IdVenda;
        partial void OnIdVendaChanging(global::System.Int32 value);
        partial void OnIdVendaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataVenda
        {
            get
            {
                return _DataVenda;
            }
            set
            {
                OnDataVendaChanging(value);
                ReportPropertyChanging("DataVenda");
                _DataVenda = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataVenda");
                OnDataVendaChanged();
            }
        }
        private global::System.DateTime _DataVenda;
        partial void OnDataVendaChanging(global::System.DateTime value);
        partial void OnDataVendaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacao
        {
            get
            {
                return _Observacao;
            }
            set
            {
                OnObservacaoChanging(value);
                ReportPropertyChanging("Observacao");
                _Observacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacao");
                OnObservacaoChanged();
            }
        }
        private global::System.String _Observacao;
        partial void OnObservacaoChanging(global::System.String value);
        partial void OnObservacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                OnIdClienteChanging(value);
                ReportPropertyChanging("IdCliente");
                _IdCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCliente");
                OnIdClienteChanged();
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdVendedor
        {
            get
            {
                return _IdVendedor;
            }
            set
            {
                OnIdVendedorChanging(value);
                ReportPropertyChanging("IdVendedor");
                _IdVendedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdVendedor");
                OnIdVendedorChanged();
            }
        }
        private global::System.Int32 _IdVendedor;
        partial void OnIdVendedorChanging(global::System.Int32 value);
        partial void OnIdVendedorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_Venda_Cliente", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("VendasModel.FK_Venda_Cliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("VendasModel.FK_Venda_Cliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("VendasModel.FK_Venda_Cliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("VendasModel.FK_Venda_Cliente", "Cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_ItemVenda_Venda", "ItemVenda")]
        public EntityCollection<ItemVenda> ItemVenda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemVenda>("VendasModel.FK_ItemVenda_Venda", "ItemVenda");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemVenda>("VendasModel.FK_ItemVenda_Venda", "ItemVenda", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_Venda_Vendedor", "Vendedor")]
        public Vendedor Vendedor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendedor>("VendasModel.FK_Venda_Vendedor", "Vendedor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendedor>("VendasModel.FK_Venda_Vendedor", "Vendedor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vendedor> VendedorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendedor>("VendasModel.FK_Venda_Vendedor", "Vendedor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vendedor>("VendasModel.FK_Venda_Vendedor", "Vendedor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VendasModel", Name="Vendedor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vendedor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vendedor object.
        /// </summary>
        /// <param name="idVendedor">Initial value of the IdVendedor property.</param>
        /// <param name="nomeVendedor">Initial value of the NomeVendedor property.</param>
        /// <param name="cPF">Initial value of the CPF property.</param>
        /// <param name="sexo">Initial value of the Sexo property.</param>
        /// <param name="dataAdmissao">Initial value of the DataAdmissao property.</param>
        /// <param name="funcao">Initial value of the Funcao property.</param>
        public static Vendedor CreateVendedor(global::System.Int32 idVendedor, global::System.String nomeVendedor, global::System.String cPF, global::System.String sexo, global::System.DateTime dataAdmissao, global::System.String funcao)
        {
            Vendedor vendedor = new Vendedor();
            vendedor.IdVendedor = idVendedor;
            vendedor.NomeVendedor = nomeVendedor;
            vendedor.CPF = cPF;
            vendedor.Sexo = sexo;
            vendedor.DataAdmissao = dataAdmissao;
            vendedor.Funcao = funcao;
            return vendedor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdVendedor
        {
            get
            {
                return _IdVendedor;
            }
            set
            {
                if (_IdVendedor != value)
                {
                    OnIdVendedorChanging(value);
                    ReportPropertyChanging("IdVendedor");
                    _IdVendedor = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdVendedor");
                    OnIdVendedorChanged();
                }
            }
        }
        private global::System.Int32 _IdVendedor;
        partial void OnIdVendedorChanging(global::System.Int32 value);
        partial void OnIdVendedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomeVendedor
        {
            get
            {
                return _NomeVendedor;
            }
            set
            {
                OnNomeVendedorChanging(value);
                ReportPropertyChanging("NomeVendedor");
                _NomeVendedor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomeVendedor");
                OnNomeVendedorChanged();
            }
        }
        private global::System.String _NomeVendedor;
        partial void OnNomeVendedorChanging(global::System.String value);
        partial void OnNomeVendedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sexo
        {
            get
            {
                return _Sexo;
            }
            set
            {
                OnSexoChanging(value);
                ReportPropertyChanging("Sexo");
                _Sexo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sexo");
                OnSexoChanged();
            }
        }
        private global::System.String _Sexo;
        partial void OnSexoChanging(global::System.String value);
        partial void OnSexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataAdmissao
        {
            get
            {
                return _DataAdmissao;
            }
            set
            {
                OnDataAdmissaoChanging(value);
                ReportPropertyChanging("DataAdmissao");
                _DataAdmissao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataAdmissao");
                OnDataAdmissaoChanged();
            }
        }
        private global::System.DateTime _DataAdmissao;
        partial void OnDataAdmissaoChanging(global::System.DateTime value);
        partial void OnDataAdmissaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Funcao
        {
            get
            {
                return _Funcao;
            }
            set
            {
                OnFuncaoChanging(value);
                ReportPropertyChanging("Funcao");
                _Funcao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Funcao");
                OnFuncaoChanged();
            }
        }
        private global::System.String _Funcao;
        partial void OnFuncaoChanging(global::System.String value);
        partial void OnFuncaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VendasModel", "FK_Venda_Vendedor", "Venda")]
        public EntityCollection<Venda> Venda
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venda>("VendasModel.FK_Venda_Vendedor", "Venda");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venda>("VendasModel.FK_Venda_Vendedor", "Venda", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
